version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - backend
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - backend
    restart: unless-stopped

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
  elasticsearch_data:

networks:
  backend:
    driver: bridge
