version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch
    environment:
      - discovery.type=single-node
    networks:
        - backend
    restart: unless-stopped

volumes:
  mongo_data:
  elasticsearch_data:

networks:
  backend:
    driver: bridge